In [11]:
import numpy as np
list_ = [ '1' ,'2' , '3' , '4' , '5' ]
array_list = np.array( object=list_)

In [12]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

ANS = Yes, there is a difference in the data types of the list_ and array_list variables. The list_ variable is a Python list containing strings, while array_list is a NumPy array.

In [14]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))

Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


In [15]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

In [18]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types in 'list_ :")
for item in list_:
    print(type(item))

print("\nData types in 'array_list :")
for item in array_list:
    print(type(item))


Data types in 'list_ :
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in 'array_list :
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [19]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)

In [21]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_, dtype = int)

ANS =  By explicitly specifying the dtype=int parameter when creating the NumPy array array_list, the elements will be converted to integers if possible. However, since the elements in the original list_ are strings representing numbers


In [24]:
print("Data types in 'list_':")
for element in list_:
    print(type(element))
print("\nData types in 'array_list':")
for element in array_list:
    print(type(element))   

Data types in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [25]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [26]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [27]:
shape = num_array.shape
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [28]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [32]:
arr=np.zeros((3,3))

In [33]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
arr.size

9

In [35]:
data=np.random.randint(0,1,(3,3))

In [36]:
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [39]:
arr1=np.eye(5,5)

In [40]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
arr1.shape

(5, 5)